# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        host: ['github-pages', 'heroku']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Build vite
      env:
        VITE_API_URL: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/api/" 
      run: |
          npm install
          npx vue-tsc --noEmit && npx vite build --base=${{ matrix.host == 'github-pages' && '/TODO-App' || '' }}/
          npm run test --if-present
      working-directory: Client

    - name: Copy static files & delete sources
      run: |
          ls -a
          mkdir -p Server/public/
          cp -a Client/dist/. Server/public/
          rm -r Client .gitignore
          
          
    - name: Deploy ðŸš€ Github Pages
      if:   matrix.host == 'github-pages'
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: Server/public # The folder the action should deploy.

    - name: Deploy ðŸš€ to Heroku
      if:   matrix.host == 'heroku'
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} # Will create app if one does not exist yet with this name
          heroku_email: ${{secrets.HEROKU_EMAIL}} # The email that you use to log in to Heroku